name: Playwright Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm install
          echo "sample1"
          pwd
          ls -al
          chmod a+x ./utils.sh
          echo "done"
      - name: Run Playwright Tests
        run: |
          npm run test-browser
