name: Playwright Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          git submodule update --init --recursive
          npm install
      - name: Run Playwright Tests
        run: |
          npm run test-browser
