name: Playwright Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Change Submodule URL to HTTPS
        run: |
          git config submodule.lexical.url https://github.com/piotrlewalski/lexical.git
          git submodule update --init --recursive
      - name: Install Dependencies
        run: |
          git submodule update --init --recursive
          npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright Tests
        run: |
          npx playwright test tests/browser/notebook/fold.spec.ts
      - name: Commit Updated Snapshots
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tests/browser/notebook/__snapshots__/
          git commit -m "Update Playwright snapshots"
          git push
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: data
          path: data/
          retention-days: 30
          
